### PR TITLE
Added georgian translation

### PR DESCRIPTION
**Pull request by Lashoo28**

### CODE REVIEW

**Review by NexiusTailer — CHANGES_REQUESTED** [review]
I've noticed little things that imo should be completed, here are they:

https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L136-L138

Those strings are empty, the translation was probably missed.

***

https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L119-L120

Here missed a word that describes checkpoint type.

***

https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L708-L871

This still in English. If you see it better leaving this part as it is, no problem, but it seemed to me it was just missed while translating the other parts.

**Comment by Lashoo28** [comment]
I corrected the missing translations. In my opinion the commands do not need translation

**Comment by Lashoo28** [comment]
If there is a problem I can translate the commands as well

**Comment by NexiusTailer** [comment]
> If there is a problem I can translate the commands as well

This would be great 🙂
Anyway, give me some time (as I'm little busy rn) so I can merge it when you make final commits

**Comment by Lashoo28** [comment]
I updated. If I missed the translation somewhere, let me know

**Comment by NexiusTailer** [comment]
Just checked the latest changes and wanna thank you again for all this. There's just a few places I found this time which is more or less important to notice so here are they:

* https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L221-L228
* https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L439-L440
* https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L732-L742
* https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L784-L785
* https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L793
* https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L803
* https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L844-L845
* https://github.com/Lashoo28/Ultimate-Creator/blob/master/v1.4.6/Georgian/creator.pwn#L859

The rest seems fully translated, so it's the final list

**Comment by NexiusTailer** [comment]
Many thanks, it was finally merged 🙂

One tiny thing I'd like to ask you to get help with, is to translate these strings in bare.pwn (which is distributed as a blank gamemode for creator.pwn in the releases section):

`Vehicle isn't created!`
`Player isn't connected!`

and

`Type /edit to enter edit mode`
`Press Enter to open the main menu`

**Comment by NexiusTailer** [comment]
Just added a build into releases section and updated credits in readme file
Thank you again!

**Pull request merged**
