### PR TITLE
fix translation

### PR DESCRIPTION
**Pull request by El-SpaceX**

### CODE REVIEW

**Comment by El-SpaceX** [comment]
I can't add or change the file, so I thought of deleting it and adding it again :p

**Comment by NexiusTailer** [comment]
Try to make next commit inside this PR (into your `patch-1` branch), adding a .pwn file with all changes you did, so all diffs could be seen via the "Files changed" tab here.

**Comment by El-SpaceX** [comment]
I believe it is correct now.

**Comment by NexiusTailer** [comment]
I made some small corrections over this update (already pushed in [c565e6b](https://github.com/NexiusTailer/Ultimate-Creator/commit/c565e6b69c013d26548158a29edc9b065df7fc4c)) and updated bare.pwn gamemode a little (changed encoding to UTF-8 just as you did it for creator.pwn). I also recompiled [release binaries](https://github.com/NexiusTailer/Ultimate-Creator/releases/tag/v1.4.6), so you could check if all is good now. Thank you for the contribution.

**Comment by El-SpaceX** [comment]
I thank you!

**Pull request closed without merging**
